# Generated by Django 5.2.7 on 2025-10-30 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expenditure_split',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='splitit_app.expendituresplit'),
        ),
    ]
